
package view;

import DAO.AlunoDao;
import Entidade.Aluno;
import ModeloTabela.Alunotablemodelo;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_OPTION;


public class TelaLista extends javax.swing.JFrame {

    /**
     * Creates new form TelaLista
     */
    public TelaLista() {
        initComponents();
        preencherTabela();
    }
    
    private void preencherTabela(){
       AlunoDao ad = new AlunoDao();
       
       Alunotablemodelo adm = new Alunotablemodelo(ad.lista());
       
       tbAlunos.setModel(adm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbAlunos = new javax.swing.JTable();
        btalterar = new javax.swing.JButton();
        btapagar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        ctpesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbAlunos);

        btalterar.setText("Alterar");
        btalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalterarActionPerformed(evt);
            }
        });

        btapagar.setText("Excluir");
        btapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btapagarActionPerformed(evt);
            }
        });

        btPesquisar.setText("Pesquisar Nome");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ctpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btPesquisar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btalterar)
                .addGap(115, 115, 115)
                .addComponent(btapagar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(ctpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPesquisar)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btalterar)
                    .addComponent(btapagar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalterarActionPerformed
            int linha = tbAlunos.getSelectedRow();
            
            if(linha < 0) {
                JOptionPane.showMessageDialog(null,"Selecione um aluno!");
            } else {
                Object o = tbAlunos.getValueAt(linha,0);
                AlunoDao cd = new AlunoDao();
                Aluno a = cd.listar("id",(int) o).get(0);
                TeladeCadastro tlc = new TeladeCadastro(a);
                tlc.setVisible(true);
                
                preencherTabela();
                
                
            }
    }//GEN-LAST:event_btalterarActionPerformed

    private void btapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btapagarActionPerformed
        int linha = tbAlunos.getSelectedRow();
        
        if (linha < 0){
            JOptionPane.showMessageDialog(rootPane,"Selecione um aluno!");
        } else {
            Object o = tbAlunos.getValueAt(linha,0);
            AlunoDao cd = new AlunoDao();
            Aluno a = cd.listar("id",(int)o).get(0);
            
           if(JOptionPane.showConfirmDialog(rootPane, "Deseja excluir?","Excluir",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
               JOptionPane.showMessageDialog(null, "Aluno excluído com sucesso!");
               cd.excluir(a);
           } else {
            }
        }        
        
    }//GEN-LAST:event_btapagarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        if(ctpesquisa.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite algo no campo");
        }else{
            
            AlunoDao ad = new AlunoDao();
            Alunotablemodelo atm = new Alunotablemodelo(ad.listar("nome",ctpesquisa.getText()));
            tbAlunos.setModel(atm);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btalterar;
    private javax.swing.JButton btapagar;
    private javax.swing.JTextField ctpesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAlunos;
    // End of variables declaration//GEN-END:variables
}
